Repository SWP391-Group5-Gemify/Gemify, pull requests merged in 2024-07, with the labels that each got.

#194 Duy - Add Payment Success (WebHook error), changing some style and add form validation on checkout
  client/package-lock.json
  client/package.json
  client/src/app/core/models/basket.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/customer/customer.service.ts
  client/src/app/core/services/dashboard/dashboard.service.ts
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.html
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.scss
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.ts
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.html
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.scss
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.ts
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.html
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.scss
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/counter-revenues-chart/counter-revenues-chart.component.html
  client/src/app/shared/components/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.html
  client/src/app/shared/components/generic-stepper/generic-stepper.component.html
  client/src/app/shared/components/managements/basket/basket.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.ts
  client/src/app/shared/components/managements/basket/table-basket-items/table-basket-items.component.html
  client/src/app/shared/components/managements/basket/table-basket-items/table-basket-items.component.ts
  client/src/app/shared/components/managements/policy/policy.component.html
  client/src/app/shared/components/managements/policy/policy.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-chart/counter-revenues-chart.component.html
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-chart/counter-revenues-chart.component.scss
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-chart/counter-revenues-chart.component.spec.ts
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-chart/counter-revenues-chart.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.html
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.scss
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.spec.ts
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.html
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.scss
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.spec.ts
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/statistic-dashboard.component.html
  client/src/app/shared/components/managements/statistic-dashboard/statistic-dashboard.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/store-revenues-yearly/store-revenues-yearly.component.html
  client/src/app/shared/components/managements/statistic-dashboard/store-revenues-yearly/store-revenues-yearly.component.scss
  client/src/app/shared/components/managements/statistic-dashboard/store-revenues-yearly/store-revenues-yearly.component.spec.ts
  client/src/app/shared/components/managements/statistic-dashboard/store-revenues-yearly/store-revenues-yearly.component.ts
  client/src/app/shared/components/mychart/mychart.component.html
  client/src/app/shared/components/mychart/mychart.component.spec.ts
  client/src/app/shared/routes/dashboards/cashier-routing.module.ts
  client/src/styles/components/_basket-summary-actions.scss
  client/src/styles/main.scss
Labels: enhancement

#201 My - Assign employee to counter #30
  API/Controllers/SaleCountersController.cs
  API/Dtos/SaleCounterDto.cs
  API/Dtos/SaleCounterToAssignDto.cs
  API/Helpers/MappingProfiles.cs
Labels: bug

#204 Promotion on Seller and on StoreOwner and Fix some service handling
  API/Controllers/AccountController.cs
  API/Controllers/PaymentsController.cs
  API/Dtos/RegisterDto.cs
  client/src/app/core/models/order.model.ts
  client/src/app/core/models/promotion.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/order/order.service.ts
  client/src/app/core/services/promotion/promotion.service.ts
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.html
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.ts
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.html
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/generic-stepper/generic-stepper.component.html
  client/src/app/shared/components/generic-table-data-source/generic-table-data-source.component.html
  client/src/app/shared/components/managements/basket/basket.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.html
  client/src/app/shared/components/managements/counters/counters.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/orders/orders.component.html
  client/src/app/shared/components/managements/products/card-product/card-product.component.scss
  client/src/app/shared/components/managements/products/card-product/card-product.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/promotions/card-promotion/card-promotion.component.html
  client/src/app/shared/components/managements/promotions/card-promotion/card-promotion.component.scss
  client/src/app/shared/components/managements/promotions/card-promotion/card-promotion.component.spec.ts
  client/src/app/shared/components/managements/promotions/card-promotion/card-promotion.component.ts
  client/src/app/shared/components/managements/promotions/promotions.component.html
  client/src/app/shared/components/managements/promotions/promotions.component.ts
Labels: feature

#207 Add saleCounter management UI (not assign yet)
  client/src/app/core/models/counter-revenue.model.ts
  client/src/app/core/models/dropdown.model.ts
  client/src/app/core/models/revenuesData.model.ts
  client/src/app/core/models/sale-counter.model.ts
  client/src/app/core/services/counter/counter.service.spec.ts
  client/src/app/core/services/counter/counter.service.ts
  client/src/app/core/services/dashboard/dashboard.service.ts
  client/src/app/shared/components/managements/counters/counters.component.ts
  client/src/app/shared/components/managements/employees/employees.component.html
  client/src/app/shared/components/managements/products-management/products-management.component.html
  client/src/app/shared/components/managements/products-management/products-management.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-chart/counter-revenues-chart.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/store-revenues-yearly/store-revenues-yearly.component.ts
Labels: feature

#209 Add counter assign mechanism
  API/Controllers/SaleCountersController.cs
  API/Dtos/SaleCounterToAssignDto.cs
  Infrastructure/Identity/AppIdentityDbContextSeed.cs
  client/src/app/app.config.ts
  client/src/app/core/interceptors/http/http.interceptor.spec.ts
  client/src/app/core/interceptors/http/http.interceptor.ts
  client/src/app/core/interceptors/loading/loading.interceptor.spec.ts
  client/src/app/core/interceptors/loading/loading.interceptor.ts
  client/src/app/core/models/sale-counter.model.ts
  client/src/app/core/services/counter/counter.service.ts
  client/src/app/core/services/employee/employee.service.ts
  client/src/app/core/services/file/file.service.ts
  client/src/app/core/services/loading/busy.service.ts
  client/src/app/core/services/product/product.service.ts
  client/src/app/shared/components/dashboards/store-owner/store-owner.component.ts
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.html
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.scss
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.spec.ts
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.ts
  client/src/app/shared/components/managements/counters/counters.component.html
  client/src/app/shared/components/managements/counters/counters.component.ts
  client/src/app/shared/components/managements/orders/order-detail/modal-change-gold-weight/modal-change-gold-weight.component.ts
  client/src/app/shared/components/managements/promotions/card-promotion/card-promotion.component.html
  client/src/app/shared/components/managements/promotions/card-promotion/card-promotion.component.ts
  client/src/app/shared/components/managements/promotions/promotions.component.ts
  client/src/app/shared/routes/dashboards/store-owner-routing.module.ts
  client/src/app/shared/routes/managements/counters-routing.module.ts
  client/src/app/shared/routes/managements/statistic-dashboard-routing.module.ts
Labels: feature

#210 My - Fix membership #134
  API/Controllers/MembershipsController.cs
Labels: enhancement

#212 Duy - Fix state management and Add membership into the sale order #203
  client/src/app/core/models/basket.model.ts
  client/src/app/core/models/membership.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/customer/customer.service.ts
  client/src/app/core/services/employee/employee.service.ts
  client/src/app/core/services/membership/membership.service.spec.ts
  client/src/app/core/services/membership/membership.service.ts
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.html
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.ts
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.html
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.ts
Labels: bug, enhancement, feature

#222 Duy - Good luck
  API/Dtos/BasketBuybackItemDto.cs
  Core/Enitities/BasketBuybackItem.cs
  client/package-lock.json
  client/package.json
  client/src/app/app.component.ts
  client/src/app/barcode-scanner/barcode-scanner.component.html
  client/src/app/barcode-scanner/barcode-scanner.component.scss
  client/src/app/barcode-scanner/barcode-scanner.component.spec.ts
  client/src/app/barcode-scanner/barcode-scanner.component.ts
  client/src/app/core/models/basket.model.ts
  client/src/app/core/models/order.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/counter/counter.service.ts
  client/src/app/core/services/employee/employee.service.ts
  client/src/app/core/services/file/file.service.ts
  client/src/app/core/services/order/order.service.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/checkout/table-basket-items-summary/table-basket-items-summary.component.ts
  client/src/app/shared/components/generic-dropdown/generic-dropdown.component.html
  client/src/app/shared/components/generic-dropdown/generic-dropdown.component.ts
  client/src/app/shared/components/managements/basket/basket.component.ts
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.ts
  client/src/app/shared/components/managements/basket/table-basket-items/table-basket-items.component.ts
  client/src/app/shared/components/managements/buyback/buyback.component.ts
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.html
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.ts
  client/src/app/shared/components/managements/counters/counters.component.html
  client/src/app/shared/components/managements/counters/counters.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/policy/policy.component.html
  client/src/app/shared/components/managements/policy/policy.component.ts
  client/src/app/shared/components/managements/product-details/product-details-management.component.ts
  client/src/app/shared/components/managements/products-management/products-management.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/app/shared/components/managements/promotions/promotions.component.html
  client/src/app/shared/components/managements/promotions/promotions.component.ts
Labels: bug, feature

#223 Exchange procedure
  Infrastructure/Services/OrderService.cs
  Infrastructure/Services/PaymentService.cs
  client/src/app/shared/components/checkout-exchange/checkout-exchange-customer/checkout-exchange-customer.component.html
  client/src/app/shared/components/checkout-exchange/checkout-exchange-customer/checkout-exchange-customer.component.scss
  client/src/app/shared/components/checkout-exchange/checkout-exchange-customer/checkout-exchange-customer.component.spec.ts
  client/src/app/shared/components/checkout-exchange/checkout-exchange-customer/checkout-exchange-customer.component.ts
  client/src/app/shared/components/checkout-exchange/checkout-exchange-payment/checkout-exchange-payment.component.html
  client/src/app/shared/components/checkout-exchange/checkout-exchange-payment/checkout-exchange-payment.component.scss
  client/src/app/shared/components/checkout-exchange/checkout-exchange-payment/checkout-exchange-payment.component.spec.ts
  client/src/app/shared/components/checkout-exchange/checkout-exchange-payment/checkout-exchange-payment.component.ts
  client/src/app/shared/components/checkout-exchange/checkout-exchange.component.html
  client/src/app/shared/components/checkout-exchange/checkout-exchange.component.scss
  client/src/app/shared/components/checkout-exchange/checkout-exchange.component.spec.ts
  client/src/app/shared/components/checkout-exchange/checkout-exchange.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/routes/dashboards/cashier-routing.module.ts
  client/src/app/shared/routes/managements/checkout-exchange-routing.module.ts
Labels: enhancement

#224 FIxing buyback, exchange logic
  client/src/app/core/interceptors/http/http.interceptor.ts
  client/src/app/core/models/basket.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/shared/components/managements/orders/order-detail/modal-change-gold-weight/modal-change-gold-weight.component.html
  client/src/app/shared/components/managements/orders/order-detail/modal-change-gold-weight/modal-change-gold-weight.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.html
  client/src/app/shared/components/managements/products/products.component.ts
Labels: bug, feature

#236 Duy - Buyback (IN), Exchange (IN, OUT) both UI and Logic
  client/src/app/shared/components/checkout-ex-bb/checkout-ex-bb-money-back/checkout-ex-bb-money-back.component.html
  client/src/app/shared/components/checkout-ex-bb/checkout-ex-bb-money-back/checkout-ex-bb-money-back.component.scss
  client/src/app/shared/components/checkout-ex-bb/checkout-ex-bb-money-back/checkout-ex-bb-money-back.component.ts
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.html
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.scss
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.ts
  client/src/app/shared/components/managements/gold-bid-ask/gold-bid-ask.component.html
  client/src/app/shared/components/managements/gold-bid-ask/gold-bid-ask.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.html
  client/src/app/shared/components/managements/statistic-dashboard/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.html
Labels: bug, enhancement, feature

#237 Duy - Add new BuyBack (OUT) sucessfully #234
  client/src/app/core/models/basket.model.ts
  client/src/app/shared/components/dashboards/repurchaser/repurchaser.component.ts
  client/src/app/shared/components/login/login.component.html
  client/src/app/shared/components/login/login.component.ts
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.html
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.scss
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.spec.ts
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.ts
  client/src/app/shared/components/managements/basket/basket.component.html
  client/src/app/shared/components/managements/buyback/buyback.component.html
  client/src/app/shared/components/managements/buyback/buyback.component.spec.ts
  client/src/app/shared/components/managements/buyback/buyback.component.ts
  client/src/app/shared/routes/dashboards/cashier-routing.module.ts
  client/src/app/shared/routes/dashboards/repurchaser-routing.module.ts
  client/src/app/shared/routes/dashboards/seller-routing.module.ts
  client/src/app/shared/routes/managements/baskets/basket-buyback-external-routing.module.ts
  client/src/app/shared/routes/managements/baskets/basket-routing.module.ts
Labels: bug, enhancement, feature

#254 Add generate PDF on order details, fix some bug on memory leaking
  API/appsettings.Development.json
  client/localhost-key.pem
  client/localhost.pem
  client/package-lock.json
  client/package.json
  client/src/app/app.config.ts
  client/src/app/core/layout/header/header.component.html
  client/src/app/core/models/order.model.ts
  client/src/app/core/services/invoice-generator/invoice-generator.service.spec.ts
  client/src/app/core/services/invoice-generator/invoice-generator.service.ts
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.html
  client/src/app/shared/components/managements/orders/order-detail/Roboto-Regular-normal.js
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.scss
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/assets/fonts/Roboto-Regular-normal.js
  client/src/assets/images/logo.png
  client/src/assets/images/signature.png
  client/src/styles/_shame.scss
  client/src/styles/main.scss
Labels: bug, feature

#255 Duy - Fix the money and conversion #251
  client/src/app/core/services/invoice-generator/invoice-generator.service.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.scss
Labels: feature

#259 Duy - Fix error on add new promotion due to same code, improve UI for readbility
  client/src/app/app.component.html
  client/src/app/app.component.ts
  client/src/app/core/layout/header/header.component.html
  client/src/app/core/layout/header/header.component.scss
  client/src/app/core/layout/header/header.component.ts
  client/src/app/core/models/modal.model.ts
  client/src/app/core/services/counter/counter.service.ts
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.html
  client/src/app/shared/components/managements/counters/card-sale-counter/card-sale-counter.component.ts
  client/src/app/shared/components/managements/counters/counters.component.html
  client/src/app/shared/components/managements/counters/counters.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.scss
  client/src/app/shared/components/managements/products/card-product/card-product.component.html
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.html
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.ts
  client/src/app/shared/components/managements/promotions/modal-create-promotion/modal-create-promotion.component.html
  client/src/app/shared/components/managements/promotions/modal-create-promotion/modal-create-promotion.component.scss
  client/src/app/shared/components/managements/promotions/modal-create-promotion/modal-create-promotion.component.spec.ts
  client/src/app/shared/components/managements/promotions/modal-create-promotion/modal-create-promotion.component.ts
  client/src/app/shared/components/managements/promotions/promotions.component.html
  client/src/app/shared/components/managements/promotions/promotions.component.ts
Labels: bug, enhancement, feature

#263 Duy - Add print feature
  client/src/app/core/models/file.model.ts
  client/src/app/core/services/file/file.service.ts
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.scss
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/policy/policy.component.html
  client/src/app/shared/components/managements/policy/policy.component.ts
Labels: enhancement, feature

#267 Duy - Fixing some styles, constraints
  client/angular.json
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/invoice-generator/invoice-generator.service.ts
  client/src/app/core/services/promotion/promotion.service.ts
  client/src/app/shared/components/barcode-scanner/barcode-scanner.component.html
  client/src/app/shared/components/barcode-scanner/barcode-scanner.component.scss
  client/src/app/shared/components/barcode-scanner/barcode-scanner.component.ts
  client/src/app/shared/components/checkout-ex-bb/checkout-ex-bb-money-back/checkout-ex-bb-money-back.component.ts
  client/src/app/shared/components/dashboards/cashier/cashier.component.html
  client/src/app/shared/components/dashboards/cashier/cashier.component.ts
  client/src/app/shared/components/dashboards/store-manager/store-manager.component.ts
  client/src/app/shared/components/dashboards/store-owner/store-owner.component.ts
  client/src/app/shared/components/generic-dropdown/generic-dropdown.component.ts
  client/src/app/shared/components/generic-stepper/generic-stepper.component.html
  client/src/app/shared/components/generic-table-data-source/generic-table-data-source.component.html
  client/src/app/shared/components/login/login.component.html
  client/src/app/shared/components/login/login.component.scss
  client/src/app/shared/components/login/login.component.ts
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.html
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.scss
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.ts
  client/src/app/shared/components/managements/basket/basket.component.html
  client/src/app/shared/components/managements/basket/basket.component.ts
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.ts
  client/src/app/shared/components/managements/employees/employees.component.ts
  client/src/app/shared/components/managements/gold-bid-ask/gold-bid-ask.component.html
  client/src/app/shared/components/managements/gold-bid-ask/gold-bid-ask.component.scss
  client/src/app/shared/components/managements/orders/order-detail/modal-change-gold-weight/modal-change-gold-weight.component.html
  client/src/app/shared/components/managements/orders/order-detail/modal-change-gold-weight/modal-change-gold-weight.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.scss
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/products-management/products-management.component.ts
  client/src/app/shared/components/managements/promotions/modal-create-promotion/modal-create-promotion.component.html
  client/src/app/shared/components/managements/promotions/promotions.component.html
  client/src/app/shared/components/managements/promotions/promotions.component.ts
  client/src/app/shared/routes/dashboards/cashier-routing.module.ts
  client/src/app/shared/routes/dashboards/store-manager-routing.module.ts
  client/src/app/show-empty-list/show-empty-list.component.html
  client/src/app/show-empty-list/show-empty-list.component.scss
  client/src/app/show-empty-list/show-empty-list.component.spec.ts
  client/src/app/show-empty-list/show-empty-list.component.ts
  client/src/styles/components/_form.scss
Labels: bug, enhancement, feature

#269 Final Pull Request
  client/src/app/core/models/basket.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/file/file.service.ts
  client/src/app/shared/components/dashboards/repurchaser/repurchaser.component.ts
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.html
  client/src/app/shared/components/managements/basket-buyback-external/basket-buyback-external.component.ts
  client/src/app/shared/components/managements/orders/order-detail/modal-change-gold-weight/modal-change-gold-weight.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/orders/orders.component.html
  client/src/app/shared/components/managements/products-management/products-management.component.html
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.html
  client/src/app/shared/routes/dashboards/repurchaser-routing.module.ts
  client/src/styles/components/_add-basket.scss
  client/src/styles/main.scss
Labels: bug
