Repository SWP391-Group5-Gemify/Gemify, pull requests merged in 2024-06, with the labels that each got.

#101 Merge modal on Edit, Create and Fixing style on Gold Chart
  client/src/app/core/components/header/header.component.html
  client/src/app/core/components/header/header.component.ts
  client/src/app/core/models/create-edit-modal.model.ts
  client/src/app/core/models/customer.model.ts
  client/src/app/core/models/gender.model.ts
  client/src/app/core/models/modal.model.ts
  client/src/app/core/models/pagination.model.ts
  client/src/app/core/models/product.model.ts
  client/src/app/core/models/role.model.ts
  client/src/app/core/models/user.model.ts
  client/src/app/core/services/auth/auth.service.ts
  client/src/app/core/services/customer/customer.service.ts
  client/src/app/core/services/employee/employee.service.ts
  client/src/app/core/services/product/product-service.service.spec.ts
  client/src/app/core/services/product/product-service.service.ts
  client/src/app/shared/components/form-edit-create-modal/form-edit-create-modal.component.html
  client/src/app/shared/components/form-edit-create-modal/form-edit-create-modal.component.ts
  client/src/app/shared/components/form-view-modal/form-view-modal.component.html
  client/src/app/shared/components/form-view-modal/form-view-modal.component.scss
  client/src/app/shared/components/form-view-modal/form-view-modal.component.spec.ts
  client/src/app/shared/components/form-view-modal/form-view-modal.component.ts
  client/src/app/shared/components/gold-chart/gold-chart.component.html
  client/src/app/shared/components/gold-chart/gold-chart.component.scss
  client/src/app/shared/components/gold-chart/gold-chart.component.ts
  client/src/app/shared/components/managements/employees/employees.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/app/shared/components/managements/warranty/warranty.component.html
  client/src/app/shared/components/managements/warranty/warranty.component.ts
  client/src/app/shared/components/my-profile/button-my-profile/button-my-profile.component.html
  client/src/app/shared/components/my-profile/button-my-profile/button-my-profile.component.ts
  client/src/app/shared/components/my-profile/page-my-profile/page-my-profile.component.scss
  client/src/app/shared/components/my-profile/page-my-profile/page-my-profile.component.ts
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.html
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.scss
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.spec.ts
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.ts
  client/src/app/shared/pipes/vietnameses-date-pipe/vietnamese-date.pipe.spec.ts
  client/src/app/shared/pipes/vietnameses-date-pipe/vietnamese-date.pipe.ts
  client/src/assets/fonts/Orbitron-SemiBold.ttf
  client/src/styles/base/_typography.scss
Labels: bug, feature

#110 Duy - Fix Bug on guards #109
  client/.vscode/settings.json
  client/src/app/app.routes.ts
  client/src/app/core/components/header/header.component.ts
  client/src/app/core/components/page-error/page-error.component.ts
  client/src/app/core/guard/auth/auth.guard.ts
  client/src/app/core/guard/roles/role.guard.ts
  client/src/app/core/services/auth/auth.service.ts
  client/src/app/shared/components/form-login/form-login.component.ts
  client/src/app/shared/routes/dashboards/appraiser-routing.module.ts
  client/src/app/shared/routes/dashboards/repurchaser-routing.module.ts
  client/src/app/shared/routes/dashboards/seller-routing.module.ts
  client/src/app/shared/routes/dashboards/store-manager-routing.module.ts
  client/src/app/shared/routes/dashboards/store-owner-routing.module.ts
Labels: bug

#111 Duy - Add grid of products card on sellers (Fetching works)
  client/src/app/app.routes.ts
  client/src/app/core/components/footer/footer.component.html
  client/src/app/core/components/footer/footer.component.scss
  client/src/app/core/components/header/header.component.html
  client/src/app/core/components/header/header.component.scss
  client/src/app/core/components/logo/logo.component.scss
  client/src/app/core/guards/auth.guard.ts
  client/src/app/core/guards/index.ts
  client/src/app/core/guards/role.guard.ts
  client/src/app/core/models/latest-gold-prices.model.ts
  client/src/app/core/models/nav-items.model.ts
  client/src/app/core/models/product.model.ts
  client/src/app/core/services/gold-chart/gold-chart.service.ts
  client/src/app/core/services/product/product-service.service.spec.ts
  client/src/app/core/services/product/product-service.service.ts
  client/src/app/core/services/product/product.service.spec.ts
  client/src/app/core/services/product/product.service.ts
  client/src/app/shared/components/card-product/card-product.component.html
  client/src/app/shared/components/card-product/card-product.component.scss
  client/src/app/shared/components/card-product/card-product.component.spec.ts
  client/src/app/shared/components/card-product/card-product.component.ts
  client/src/app/shared/components/dashboards/cashier/cashier.component.html
  client/src/app/shared/components/dashboards/cashier/cashier.component.ts
  client/src/app/shared/components/dashboards/seller/seller.component.html
  client/src/app/shared/components/dashboards/seller/seller.component.ts
  client/src/app/shared/components/dashboards/store-owner/store-owner.component.ts
  client/src/app/shared/components/gold-chart/gold-chart.component.html
  client/src/app/shared/components/gold-chart/gold-chart.component.scss
  client/src/app/shared/components/gold-chart/gold-chart.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.scss
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/app/shared/routes/dashboards/appraiser-routing.module.ts
  client/src/app/shared/routes/dashboards/cashier-routing.module.ts
  client/src/app/shared/routes/dashboards/repurchaser-routing.module.ts
  client/src/app/shared/routes/dashboards/seller-routing.module.ts
  client/src/app/shared/routes/dashboards/store-manager-routing.module.ts
  client/src/app/shared/routes/dashboards/store-owner-routing.module.ts
  client/src/app/shared/routes/managements/buyback-routing.module.ts
  client/src/app/shared/routes/managements/counters-routing.module.ts
  client/src/app/shared/routes/managements/customers-routing.module.ts
  client/src/app/shared/routes/managements/employees-routing.module.ts
  client/src/app/shared/routes/managements/exchange-routing.module.ts
  client/src/app/shared/routes/managements/gold-bid-ask-routing.module.ts
  client/src/app/shared/routes/managements/loyalty-routing.module.ts
  client/src/app/shared/routes/managements/orders-routing.module.ts
  client/src/app/shared/routes/managements/products-routing.module.ts
  client/src/app/shared/routes/managements/promotions-routing.module.ts
  client/src/app/shared/routes/managements/statistic-dashboard-routing.module.ts
  client/src/app/shared/routes/managements/warranty-routing.module.ts
  client/src/styles/abstracts/_mixins.scss
  client/src/styles/abstracts/_variables.scss
  client/src/styles/base/_base.scss
  client/src/styles/base/_utilities.scss
  client/src/styles/layout/_grid.scss
  client/src/styles/layout/_sidenav-content.scss
  client/src/styles/main.scss
Labels: feature

#116 Hotfix on folder structure
  client/src/app/app.component.ts
  client/src/app/app.routes.ts
  client/src/app/core/layout/footer/footer.component.html
  client/src/app/core/layout/footer/footer.component.scss
  client/src/app/core/layout/footer/footer.component.spec.ts
  client/src/app/core/layout/footer/footer.component.ts
  client/src/app/core/layout/header/header.component.html
  client/src/app/core/layout/header/header.component.scss
  client/src/app/core/layout/header/header.component.spec.ts
  client/src/app/core/layout/header/header.component.ts
  client/src/app/core/layout/logo/logo.component.html
  client/src/app/core/layout/logo/logo.component.scss
  client/src/app/core/layout/logo/logo.component.spec.ts
  client/src/app/core/layout/logo/logo.component.ts
  client/src/app/core/layout/page-error/page-error.component.html
  client/src/app/core/layout/page-error/page-error.component.scss
  client/src/app/core/layout/page-error/page-error.component.spec.ts
  client/src/app/core/layout/page-error/page-error.component.ts
  client/src/app/shared/components/generic-stacked-chips/generic-stacked-chips.component.ts
  client/src/app/shared/components/managements/products/card-product/card-product.component.html
  client/src/app/shared/components/managements/products/card-product/card-product.component.scss
  client/src/app/shared/components/managements/products/card-product/card-product.component.spec.ts
  client/src/app/shared/components/managements/products/card-product/card-product.component.ts
  client/src/app/shared/components/managements/products/products.component.ts
Labels: bug

#122 Duy - Add maintain the user session when closing the website #121
  client/.editorconfig
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/app.config.ts
  client/src/app/app.routes.ts
  client/src/app/core/guards/auth.guard.ts
  client/src/app/core/interceptors/http/http-interceptor.interceptor.spec.ts
  client/src/app/core/interceptors/http/http-interceptor.interceptor.ts
  client/src/app/core/interceptors/loading/loading-interceptor.interceptor.spec.ts
  client/src/app/core/interceptors/loading/loading-interceptor.interceptor.ts
  client/src/app/core/services/auth/auth.service.ts
  client/src/app/shared/components/form-login/form-login.component.ts
  client/src/app/shared/components/login/login.component.html
  client/src/app/shared/components/login/login.component.scss
  client/src/app/shared/components/login/login.component.spec.ts
  client/src/app/shared/components/login/login.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.scss
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/styles/components/_button.scss
Labels: bug

#123 Duy - Khanh Le - Merge Product, Cashier (services), Order Details, Orders
  API/Controllers/AccountController.cs
  API/Controllers/OrdersController.cs
  API/Dtos/OrderToReturnDto.cs
  API/Helpers/MappingProfiles.cs
  Core/Interfaces/IOrderService.cs
  Core/Specifications/Orders/OrderSpecParams.cs
  Core/Specifications/Orders/OrdersSpecification.cs
  Infrastructure/Data/SeedData/PromotionSeedData.json
  Infrastructure/Services/OrderService.cs
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/app.component.ts
  client/src/app/app.routes.ts
  client/src/app/core/guards/auth.guard.ts
  client/src/app/core/guards/role.guard.ts
  client/src/app/core/interceptors/http/http-interceptor.interceptor.ts
  client/src/app/core/layout/header/header.component.ts
  client/src/app/core/layout/page-error/page-error.component.ts
  client/src/app/core/models/basket.ts
  client/src/app/core/models/employee.model.ts
  client/src/app/core/models/error-response.model.ts
  client/src/app/core/models/order.model.ts
  client/src/app/core/models/route-error-response.model.ts
  client/src/app/core/models/user.model.ts
  client/src/app/core/services/basket/basket.service.spec.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/orders/orders.service.spec.ts
  client/src/app/core/services/orders/orders.service.ts
  client/src/app/core/services/product/product-service.service.ts
  client/src/app/shared/components/dashboards/seller/seller.component.ts
  client/src/app/shared/components/form-login/form-login.component.scss
  client/src/app/shared/components/generic-dropdown/generic-dropdown.component.ts
  client/src/app/shared/components/generic-search/generic-search.component.ts
  client/src/app/shared/components/generic-table-data-source/generic-table-data-source.component.html
  client/src/app/shared/components/generic-table-data-source/generic-table-data-source.component.ts
  client/src/app/shared/components/managements/basket/basket.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.scss
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.spec.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/orders/orders.component.html
  client/src/app/shared/components/managements/orders/orders.component.scss
  client/src/app/shared/components/managements/orders/orders.component.ts
  client/src/app/shared/components/managements/products/card-product/card-product.component.html
  client/src/app/shared/components/managements/products/card-product/card-product.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/app/shared/routes/dashboards/seller-routing.module.ts
  client/src/app/shared/routes/managements/orders-routing.module.ts
  client/src/styles/components/_button.scss
  client/src/styles/components/_filter-controls.scss
  client/src/styles/layout/_sidenav-content.scss
Labels: feature

#126 Merge dev_upload_file into dev with selected source code only
  API/Controllers/OrdersController.cs
  Core/Enitities/OrderAggregate/Order.cs
  Core/Specifications/Orders/OrderItemSpecification.cs
  Infrastructure/Services/OrderService.cs
  client/package-lock.json
  client/package.json
  client/src/app/app.config.ts
  client/src/app/core/services/upload-file/upload-file.service.spec.ts
  client/src/app/core/services/upload-file/upload-file.service.ts
  client/src/app/shared/components/managements/warranty/warranty.component.html
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.html
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.ts
  client/src/environments/environment.development.ts
  client/src/environments/environment.ts
Labels: feature

#129 Merge modal, firebase, notification and fixing some UI
  client/package-lock.json
  client/package.json
  client/src/app/app.config.ts
  client/src/app/app.routes.ts
  client/src/app/core/layout/header/header.component.ts
  client/src/app/core/models/employee.model.ts
  client/src/app/core/models/modal.model.ts
  client/src/app/core/services/product/product.service.ts
  client/src/app/core/services/snackbar/snackbar.service.spec.ts
  client/src/app/core/services/snackbar/snackbar.service.ts
  client/src/app/core/services/upload-file/upload-file.service.spec.ts
  client/src/app/core/services/upload-file/upload-file.service.ts
  client/src/app/shared/components/generic-dropdown/generic-dropdown.component.ts
  client/src/app/shared/components/generic-search/generic-search.component.ts
  client/src/app/shared/components/generic-table-data-source/generic-table-data-source.component.scss
  client/src/app/shared/components/managements/employees/employees.component.html
  client/src/app/shared/components/managements/employees/employees.component.ts
  client/src/app/shared/components/managements/employees/modal-edit-create-employee/modal-edit-create-employee.component.html
  client/src/app/shared/components/managements/employees/modal-edit-create-employee/modal-edit-create-employee.component.scss
  client/src/app/shared/components/managements/employees/modal-edit-create-employee/modal-edit-create-employee.component.ts
  client/src/app/shared/components/managements/orders/orders.component.ts
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.html
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.ts
  client/src/environments/environment.development.ts
  client/src/environments/environment.ts
  client/src/styles/components/_form.scss
Labels: bug

#131 Merge complete CRUD generic modal tested on Employee
  client/src/app/core/layout/header/header.component.ts
  client/src/app/core/models/modal.model.ts
  client/src/app/core/services/auth/auth.service.ts
  client/src/app/core/services/file/file.service.spec.ts
  client/src/app/core/services/file/file.service.ts
  client/src/app/core/services/snackbar/snackbar.service.spec.ts
  client/src/app/core/services/snackbar/snackbar.service.ts
  client/src/app/shared/components/managements/employees/employees.component.ts
  client/src/app/shared/components/managements/employees/modal-edit-create-employee/modal-edit-create-employee.component.html
  client/src/app/shared/components/managements/employees/modal-edit-create-employee/modal-edit-create-employee.component.ts
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.html
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.scss
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.spec.ts
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.ts
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.ts
  client/src/styles/components/_form.scss
Labels: enhancement, feature

#143 Ignore SSL, Environment
  client/.gitignore
  client/src/environments/environment.development.ts
  client/src/environments/environment.ts
  client/ssl/localhost-key.pem
  client/ssl/localhost.pem
Labels: feature

#144 Duy - completely remove Appraiser
  client/src/app/app.routes.ts
  client/src/app/core/models/role.model.ts
  client/src/app/shared/components/dashboards/appraiser/appraiser.component.html
  client/src/app/shared/components/dashboards/appraiser/appraiser.component.scss
  client/src/app/shared/components/dashboards/appraiser/appraiser.component.spec.ts
  client/src/app/shared/components/dashboards/appraiser/appraiser.component.ts
  client/src/app/shared/components/login/login.component.ts
  client/src/app/shared/routes/dashboards/appraiser-routing.module.ts
Labels: enhancement

#145 Duy - Hotfix - Mapping items to saleItems
  client/src/app/app.component.ts
  client/src/app/core/models/basket.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/shared/components/managements/basket/basket.component.ts
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.html
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.scss
  client/src/styles/components/_form.scss
Labels: bug

#146 Duy - Completely remove Appraiser routes
  client/src/app/shared/components/dashboards/appraiser/appraiser.component.html
  client/src/app/shared/components/dashboards/appraiser/appraiser.component.scss
  client/src/app/shared/components/dashboards/appraiser/appraiser.component.spec.ts
  client/src/app/shared/components/dashboards/appraiser/appraiser.component.ts
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.html
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.scss
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.spec.ts
  client/src/app/shared/components/managements/employees/modal-view-employee/modal-view-employee.component.ts
  client/src/app/shared/routes/dashboards/appraiser-routing.module.ts
Labels: bug

#148 Add Products management on Store Owner, Gold Services
  client/src/app/core/layout/header/header.component.ts
  client/src/app/core/models/gold.model.ts
  client/src/app/core/models/product.model.ts
  client/src/app/core/services/gold/gold.service.ts
  client/src/app/core/services/orders/orders.service.ts
  client/src/app/core/services/product/product.service.ts
  client/src/app/shared/components/dashboards/store-manager/store-manager.component.ts
  client/src/app/shared/components/dashboards/store-owner/store-owner.component.ts
  client/src/app/shared/components/generic-search/generic-search.component.html
  client/src/app/shared/components/generic-table-data-source/generic-table-data-source.component.html
  client/src/app/shared/components/managements/employees/modal-view-current-user/modal-view-current-user.component.html
  client/src/app/shared/components/managements/employees/modal-view-current-user/modal-view-current-user.component.scss
  client/src/app/shared/components/managements/employees/modal-view-current-user/modal-view-current-user.component.spec.ts
  client/src/app/shared/components/managements/employees/modal-view-current-user/modal-view-current-user.component.ts
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.html
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.scss
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.spec.ts
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.ts
  client/src/app/shared/components/managements/products-management/products-management.component.html
  client/src/app/shared/components/managements/products-management/products-management.component.scss
  client/src/app/shared/components/managements/products-management/products-management.component.spec.ts
  client/src/app/shared/components/managements/products-management/products-management.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/app/shared/routes/dashboards/store-manager-routing.module.ts
  client/src/app/shared/routes/dashboards/store-owner-routing.module.ts
  client/src/app/shared/routes/managements/product-details-routing.module.ts
  client/src/app/shared/routes/managements/products-management-routing.module.ts
  client/src/styles/components/_form.scss
  client/tsconfig.json
Labels: enhancement

#150 Add Product Details, and Product Management
  client/src/app/core/models/gold.model.ts
  client/src/app/core/services/gold/gold.service.ts
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.scss
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.html
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.scss
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.ts
  client/src/styles/abstracts/_variables.scss
  client/src/styles/layout/_sidenav-content.scss
Labels: feature

#160 Fix upload file (convert into observable, and disable on product)
  client/src/app/core/layout/header/header.component.html
  client/src/app/core/layout/header/header.component.ts
  client/src/app/core/services/file/file.service.ts
  client/src/app/core/services/product/product.service.ts
  client/src/app/shared/components/dashboards/store-owner/store-owner.component.ts
  client/src/app/shared/components/generic-table-data-source/generic-table-data-source.component.html
  client/src/app/shared/components/generic-table-data-source/generic-table-data-source.component.ts
  client/src/app/shared/components/gold-chart/gold-chart.component.html
  client/src/app/shared/components/gold-chart/gold-chart.component.scss
  client/src/app/shared/components/managements/employees/employees.component.html
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.html
  client/src/app/shared/components/managements/products-management/product-details-management/product-details-management.component.scss
  client/src/app/shared/components/managements/products-management/products-management.component.html
  client/src/app/shared/components/managements/products-management/products-management.component.ts
  client/src/app/shared/components/managements/warranty/warranty.component.html
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.html
  client/src/app/shared/components/upload-file-pdf/upload-file-pdf.component.ts
  client/src/styles/components/_button.scss
Labels: bug, feature

#163 Duy - Add delete basket, fix some bugs
  client/src/app/core/guards/auth.guard.ts
  client/src/app/core/guards/role.guard.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/shared/components/dashboards/seller/seller.component.ts
  client/src/app/shared/components/generic-dropdown/generic-dropdown.component.ts
  client/src/app/shared/components/managements/basket/basket.component.html
  client/src/app/shared/components/managements/basket/basket.component.ts
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/product-details/product-details-management.component.html
  client/src/app/shared/components/managements/product-details/product-details-management.component.scss
  client/src/app/shared/components/managements/product-details/product-details-management.component.spec.ts
  client/src/app/shared/components/managements/product-details/product-details-management.component.ts
  client/src/app/shared/components/managements/products/card-product/card-product.component.html
  client/src/app/shared/components/managements/products/card-product/card-product.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/app/shared/routes/dashboards/cashier-routing.module.ts
  client/src/app/shared/routes/dashboards/repurchaser-routing.module.ts
  client/src/app/shared/routes/dashboards/seller-routing.module.ts
  client/src/app/shared/routes/dashboards/store-manager-routing.module.ts
  client/src/app/shared/routes/dashboards/store-owner-routing.module.ts
  client/src/app/shared/routes/managements/orders-routing.module.ts
  client/src/app/shared/routes/managements/product-details-routing.module.ts
  client/src/app/shared/routes/managements/products-routing.module.ts
Labels: bug, feature

#164 Fix bug on checkout page for current baskets source
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.scss
  client/src/app/shared/components/checkout/checkout.component.spec.ts
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/managements/basket/basket.component.html
  client/src/app/shared/components/managements/basket/basket.component.ts
  client/src/app/shared/components/managements/basket/card-basket-item/card-basket-item.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.html
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/orders/orders.component.ts
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.html
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.ts
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/app/shared/routes/dashboards/cashier-routing.module.ts
  client/src/app/shared/routes/managements/checkout-routing.module.ts
Labels: bug

#166 Add Stepper, customer and payment template
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.html
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.scss
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.spec.ts
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.ts
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.html
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.scss
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.spec.ts
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.ts
  client/src/app/shared/components/checkout/checkout-success/checkout-success.component.html
  client/src/app/shared/components/checkout/checkout-success/checkout-success.component.scss
  client/src/app/shared/components/checkout/checkout-success/checkout-success.component.spec.ts
  client/src/app/shared/components/checkout/checkout-success/checkout-success.component.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.scss
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/checkout/table-basket-items-summary/table-basket-items-summary.component.html
  client/src/app/shared/components/checkout/table-basket-items-summary/table-basket-items-summary.component.scss
  client/src/app/shared/components/checkout/table-basket-items-summary/table-basket-items-summary.component.spec.ts
  client/src/app/shared/components/checkout/table-basket-items-summary/table-basket-items-summary.component.ts
  client/src/app/shared/components/generic-stepper/generic-stepper.component.html
  client/src/app/shared/components/generic-stepper/generic-stepper.component.scss
  client/src/app/shared/components/generic-stepper/generic-stepper.component.spec.ts
  client/src/app/shared/components/generic-stepper/generic-stepper.component.ts
  client/src/app/shared/components/managements/basket/basket.component.ts
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.ts
  client/src/app/shared/components/managements/basket/table-basket-items/table-basket-items.component.html
  client/src/app/shared/components/managements/basket/table-basket-items/table-basket-items.component.scss
  client/src/app/shared/components/managements/basket/table-basket-items/table-basket-items.component.spec.ts
  client/src/app/shared/components/managements/basket/table-basket-items/table-basket-items.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.scss
  client/src/app/shared/components/managements/product-details/product-details-management.component.html
  client/src/styles/components/_button.scss
  client/src/styles/components/_table-basket-items.scss
  client/src/styles/main.scss
Labels: feature

#168 Duy - Fix basket, create basket summary on payment checkout
  client/src/app/core/interceptors/http/http-interceptor.interceptor.ts
  client/src/app/core/services/customer/customer.service.ts
  client/src/app/core/services/orders/orders.service.ts
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.html
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.scss
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.ts
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.html
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.scss
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/checkout/table-basket-items-summary/table-basket-items-summary.component.html
  client/src/app/shared/components/checkout/table-basket-items-summary/table-basket-items-summary.component.scss
  client/src/app/shared/components/generic-stepper/generic-stepper.component.html
  client/src/app/shared/components/generic-stepper/generic-stepper.component.scss
  client/src/app/shared/components/login/login.component.html
  client/src/app/shared/components/managements/employees/modal-edit-create-employee/modal-edit-create-employee.component.html
  client/src/app/shared/components/managements/employees/modal-edit-create-employee/modal-edit-create-employee.component.ts
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.html
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.ts
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.scss
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/styles/components/_button.scss
  client/src/styles/components/_form.scss
  client/src/styles/layout/_grid.scss
Labels: bug, feature

#179 Duy - Promotion checkout and services
  client/src/app/core/models/promotion.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/orders/orders.service.ts
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.html
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.scss
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.html
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.html
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.scss
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.spec.ts
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/generic-stepper/generic-stepper.component.html
  client/src/app/shared/components/generic-stepper/generic-stepper.component.scss
  client/src/app/shared/components/managements/products/products.component.html
  client/src/app/shared/components/managements/products/products.component.ts
Labels: feature

#180 Duy - Fix bug on current basket, add previous and forward stepper, create order
  client/package-lock.json
  client/package.json
  client/src/app/core/interceptors/loading/loading-interceptor.interceptor.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/customer/customer.service.ts
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.html
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.scss
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.ts
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.html
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.ts
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.html
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.ts
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/checkout/table-basket-items-summary/table-basket-items-summary.component.html
  client/src/app/shared/components/generic-stepper/generic-stepper.component.html
  client/src/app/shared/components/generic-stepper/generic-stepper.component.ts
  client/src/app/shared/components/managements/basket/basket.component.ts
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.ts
  client/src/app/shared/components/managements/products/modal-create-new-basket/modal-create-new-basket.component.html
  client/src/app/shared/components/managements/products/products.component.ts
  client/src/app/shared/routes/dashboards/cashier-routing.module.ts
  client/src/app/shared/utils/EnumUtils.ts
  client/src/styles/components/_basket-summary-actions.scss
  client/src/styles/components/_button.scss
  client/src/styles/main.scss
Labels: bug, feature

#181 Duy - createOrder, fix some styles #156
  client/src/app/core/services/customer/customer.service.ts
  client/src/app/core/services/order/order.service.spec.ts
  client/src/app/core/services/order/order.service.ts
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.html
  client/src/app/shared/components/checkout/checkout-customer/checkout-customer.component.ts
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.html
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.ts
  client/src/app/shared/components/checkout/checkout-promotion/checkout-promotion.component.html
  client/src/app/shared/components/checkout/checkout.component.html
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/generic-search/generic-search.component.html
  client/src/app/shared/components/managements/basket/card-basket/card-basket.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/orders/orders.component.ts
  client/src/styles/components/_button.scss
Labels: bug, feature

#183 Duy - Payment Intent, Create Sale orders, Fix bugs
  client/src/app/app.component.ts
  client/src/app/core/models/basket.model.ts
  client/src/app/core/models/product.model.ts
  client/src/app/core/services/basket/basket.service.ts
  client/src/app/core/services/gold/gold.service.ts
  client/src/app/shared/components/checkout/checkout-payment/checkout-payment.component.ts
  client/src/app/shared/components/checkout/checkout.component.ts
  client/src/app/shared/components/managements/customers/customers.component.ts
  client/src/app/shared/components/managements/employees/modal-view-current-user/modal-view-current-user.component.ts
  client/src/app/shared/components/managements/gold-bid-ask/gold-bid-ask.component.html
  client/src/app/shared/components/managements/gold-bid-ask/gold-bid-ask.component.ts
  client/src/app/shared/components/managements/orders/order-detail/order-detail.component.ts
  client/src/app/shared/components/managements/products/card-product/card-product.component.scss
  client/src/app/shared/components/managements/products/products.component.ts
Labels: bug, feature

#187 Statistic dashboard
  API/Controllers/DashboardController.cs
  API/Extensions/ApplicationServicesExtensions.cs
  Core/Enitities/DashboardCounterRevenue.cs
  Core/Enitities/SaleCounterRevenueByMonth.cs
  Core/Enitities/SaleCounterRevenueYearly.cs
  Core/Enitities/SaleRevenue.cs
  Core/Interfaces/ISaleCounterRevenueService.cs
  Core/Interfaces/ISaleRevenueService.cs
  Core/Specifications/Counters/SaleCounterRevenueSpecification.cs
  Core/Specifications/Counters/SaleCounterSpecification.cs
  Infrastructure/Data/SeedData/SaleCounterRevenue.json
  Infrastructure/Data/StoreContext.cs
  Infrastructure/Data/StoreContextSeed.cs
  Infrastructure/Services/SaleCounterRevenueService.cs
  Infrastructure/Services/SaleRevenueService.cs
  client/localhost-key.pem
  client/localhost.pem
  client/package-lock.json
  client/package.json
  client/src/app/core/models/counter-revenue.model.ts
  client/src/app/core/models/revenuesData.model.ts
  client/src/app/core/services/dashboard/dashboard.service.spec.ts
  client/src/app/core/services/dashboard/dashboard.service.ts
  client/src/app/shared/components/counter-revenues-chart/counter-revenues-chart.component.html
  client/src/app/shared/components/counter-revenues-chart/counter-revenues-chart.component.scss
  client/src/app/shared/components/counter-revenues-chart/counter-revenues-chart.component.spec.ts
  client/src/app/shared/components/counter-revenues-chart/counter-revenues-chart.component.ts
  client/src/app/shared/components/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.html
  client/src/app/shared/components/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.scss
  client/src/app/shared/components/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.spec.ts
  client/src/app/shared/components/counter-revenues-in-a-month-chart/counter-revenues-in-a-month-chart.component.ts
  client/src/app/shared/components/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.html
  client/src/app/shared/components/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.scss
  client/src/app/shared/components/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.spec.ts
  client/src/app/shared/components/counter-revenues-yearly-chart/counter-revenues-yearly-chart.component.ts
  client/src/app/shared/components/managements/statistic-dashboard/statistic-dashboard.component.html
  client/src/app/shared/components/managements/statistic-dashboard/statistic-dashboard.component.ts
  client/src/app/shared/components/mychart/mychart.component.html
  client/src/app/shared/components/mychart/mychart.component.scss
  client/src/app/shared/components/mychart/mychart.component.spec.ts
  client/src/app/shared/components/mychart/mychart.component.ts
Labels: feature
